import type { ViewportPreset } from './schema';

export const VIEWPORTS = [
  {
    id: 'phone',
    label: 'iPhone 14 Pro Max — 430 × 932',
    width: 430,
    height: 932,
    deviceScaleFactor: 3,
    mobile: true,
    touch: true,
  },
  {
    id: 'iphone-standard',
    label: 'iPhone standard — 390 × 844',
    width: 390,
    height: 844,
    deviceScaleFactor: 3,
    mobile: true,
    touch: true,
  },
  {
    id: 'iphone-compact',
    label: 'iPhone compact — 375 × 667',
    width: 375,
    height: 667,
    deviceScaleFactor: 2,
    mobile: true,
    touch: true,
  },
  {
    id: 'android',
    label: 'Android — 412 × 915',
    width: 412,
    height: 915,
    deviceScaleFactor: 2.625,
    mobile: true,
    touch: true,
  },
  {
    id: 'tablet',
    label: 'Tablet — 768 × 1024',
    width: 768,
    height: 1024,
    deviceScaleFactor: 2,
    mobile: true,
    touch: true,
  },
  {
    id: 'laptop',
    label: 'Laptop — 1280 × 800',
    width: 1280,
    height: 800,
    deviceScaleFactor: 1,
    mobile: false,
    touch: false,
  },
  {
    id: 'desktop',
    label: 'Desktop — 1440 × 1000',
    width: 1440,
    height: 1000,
    deviceScaleFactor: 1,
    mobile: false,
    touch: false,
  },
] as const satisfies readonly ViewportPreset[];
